# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teamDataManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 384)
        Form.setStyleSheet("background-color:rgb(70, 70, 70);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 361))
        self.label.setStyleSheet("background-color:rgba(0,0,0,150);\n"
"border-radius:15px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 151, 361))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,160);\n"
"border-radius:15px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(340, 10, 161, 361))
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,160);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 113, 20))
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:white;\n"
"padding-bottom:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 30, 113, 20))
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:white;\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(190, 150, 131, 21))
        self.pushButton.setStyleSheet("QPushButton {\n"
"  color: #ffffff;\n"
"  background-color: #222222;\n"
"  border: 1px solid black;\n"
"  border-radius: 5px;\n"
"  font-size: 12px;\n"
"  font-weight: bold;\n"
" \n"
"  transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #555555;\n"
"  box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.1);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  background-color: #333333;\n"
"  box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.2);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton.glow {\n"
"  animation: glow 1s ease-in-out infinite alternate;\n"
"}\n"
"\n"
"@keyframes glow {\n"
"  from {\n"
"    box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  }\n"
"  to {\n"
"    box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  }\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 90, 80, 18))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(30, 150, 55, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 190, 80, 18))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 60, 80, 18))
        self.pushButton_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:white;\n"
"padding-bottom:7px;\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 90, 131, 21))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"  color: #ffffff;\n"
"  background-color: #222222;\n"
"  border: 1px solid black;\n"
"  border-radius: 5px;\n"
"  font-size: 12px;\n"
"  font-weight: bold;\n"
" \n"
"  transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #555555;\n"
"  box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.1);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  background-color: #333333;\n"
"  box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.2);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton.glow {\n"
"  animation: glow 1s ease-in-out infinite alternate;\n"
"}\n"
"\n"
"@keyframes glow {\n"
"  from {\n"
"    box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  }\n"
"  to {\n"
"    box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  }\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 120, 131, 21))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"  color: #ffffff;\n"
"  background-color: #222222;\n"
"  border: 1px solid black;\n"
"  border-radius: 5px;\n"
"  font-size: 12px;\n"
"  font-weight: bold;\n"
" \n"
"  transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #555555;\n"
"  box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.1);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  background-color: #333333;\n"
"  box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.2);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton.glow {\n"
"  animation: glow 1s ease-in-out infinite alternate;\n"
"}\n"
"\n"
"@keyframes glow {\n"
"  from {\n"
"    box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  }\n"
"  to {\n"
"    box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  }\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(200, 340, 111, 21))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"  color: #ffffff;\n"
"  background-color: #222222;\n"
"  border: 1px solid black;\n"
"  border-radius: 5px;\n"
"  font-size: 12px;\n"
"  font-weight: bold;\n"
" \n"
"  transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #555555;\n"
"  box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.1);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  background-color: #333333;\n"
"  box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.2);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton.glow {\n"
"  animation: glow 1s ease-in-out infinite alternate;\n"
"}\n"
"\n"
"@keyframes glow {\n"
"  from {\n"
"    box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  }\n"
"  to {\n"
"    box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  }\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 270, 113, 20))
        self.lineEdit_4.setStyleSheet(" background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:white;\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 310, 55, 22))
        self.comboBox_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:white;\n"
"padding-bottom:7px;\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(24, "")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(270, 310, 55, 22))
        self.comboBox_4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:white;\n"
"padding-bottom:7px;\n"
"")
        self.comboBox_4.setObjectName("comboBox_4")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 180, 131, 21))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"  color: #ffffff;\n"
"  background-color: #222222;\n"
"  border: 1px solid black;\n"
"  border-radius: 5px;\n"
"  font-size: 12px;\n"
"  font-weight: bold;\n"
" \n"
"  transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #555555;\n"
"  box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.1);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  background-color: #333333;\n"
"  box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.2);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton.glow {\n"
"  animation: glow 1s ease-in-out infinite alternate;\n"
"}\n"
"\n"
"@keyframes glow {\n"
"  from {\n"
"    box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  }\n"
"  to {\n"
"    box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  }\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setGeometry(QtCore.QRect(190, 210, 131, 22))
        self.comboBox_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:white;\n"
"padding-bottom:7px;\n"
"")
        self.comboBox_5.setObjectName("comboBox_5")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(200, 250, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(510, 10, 161, 361))
        self.label_4.setStyleSheet("background-color:rgba(0,0,0,160);\n"
"border-radius:15px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(360, 90, 121, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setGeometry(QtCore.QRect(350, 50, 55, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        self.comboBox_7.setGeometry(QtCore.QRect(440, 50, 55, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(370, 120, 101, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(360, 150, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 180, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(370, 210, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(370, 240, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(540, 30, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(370, 340, 111, 21))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"  color: #ffffff;\n"
"  background-color: #222222;\n"
"  border: 1px solid black;\n"
"  border-radius: 5px;\n"
"  font-size: 12px;\n"
"  font-weight: bold;\n"
" \n"
"  transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #555555;\n"
"  box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.1);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  background-color: #333333;\n"
"  box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.2);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton.glow {\n"
"  animation: glow 1s ease-in-out infinite alternate;\n"
"}\n"
"\n"
"@keyframes glow {\n"
"  from {\n"
"    box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  }\n"
"  to {\n"
"    box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  }\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(540, 340, 111, 21))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"  color: #ffffff;\n"
"  background-color: #222222;\n"
"  border: 1px solid black;\n"
"  border-radius: 5px;\n"
"  font-size: 12px;\n"
"  font-weight: bold;\n"
" \n"
"  transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #555555;\n"
"  box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.1);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  background-color: #333333;\n"
"  box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  transform: scale(1.2);  /* increased hover effect */\n"
"}\n"
"\n"
"QPushButton.glow {\n"
"  animation: glow 1s ease-in-out infinite alternate;\n"
"}\n"
"\n"
"@keyframes glow {\n"
"  from {\n"
"    box-shadow: 0 0 20px #ffffff;  /* increased shadow size */\n"
"  }\n"
"  to {\n"
"    box-shadow: 0 0 30px #ffffff;  /* increased shadow size */\n"
"  }\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.comboBox_8 = QtWidgets.QComboBox(Form)
        self.comboBox_8.setGeometry(QtCore.QRect(550, 120, 101, 22))
        self.comboBox_8.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:white;\n"
"padding-bottom:7px;\n"
"")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setItemText(24, "")
        self.comboBox_9 = QtWidgets.QComboBox(Form)
        self.comboBox_9.setGeometry(QtCore.QRect(520, 190, 131, 22))
        self.comboBox_9.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:white;\n"
"padding-bottom:7px;\n"
"")
        self.comboBox_9.setObjectName("comboBox_9")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.comboBox.raise_()
        self.pushButton_3.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_4.raise_()
        self.pushButton_8.raise_()
        self.lineEdit_4.raise_()
        self.comboBox_2.raise_()
        self.comboBox_4.raise_()
        self.pushButton_9.raise_()
        self.comboBox_5.raise_()
        self.line.raise_()
        self.label_4.raise_()
        self.comboBox_3.raise_()
        self.comboBox_6.raise_()
        self.comboBox_7.raise_()
        self.dateTimeEdit.raise_()
        self.line_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.comboBox_8.raise_()
        self.comboBox_9.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Team Name"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Search Player"))
        self.pushButton.setText(_translate("Form", "Add Assist"))
        self.pushButton_2.setText(_translate("Form", "ADD"))
        self.pushButton_3.setText(_translate("Form", "DELETE"))
        self.pushButton_5.setText(_translate("Form", "Select"))
        self.pushButton_6.setText(_translate("Form", "Add Red Card"))
        self.pushButton_4.setText(_translate("Form", "Add Goal"))
        self.pushButton_8.setText(_translate("Form", "Add"))
        self.lineEdit_4.setText(_translate("Form", "Enter Name of Player"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", " "))
        self.comboBox_2.setPlaceholderText(_translate("Form", "Team"))
        self.comboBox_2.setItemText(0, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(1, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(2, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(3, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(4, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(5, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(6, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(7, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(8, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(9, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(10, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(11, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(12, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(13, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(14, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(15, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(16, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(17, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(18, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(19, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(20, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(21, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(22, _translate("Form", "New Item"))
        self.comboBox_2.setItemText(23, _translate("Form", "New Item"))
        self.comboBox_4.setPlaceholderText(_translate("Form", "Position"))
        self.pushButton_9.setText(_translate("Form", "Add Yellow"))
        self.comboBox_5.setPlaceholderText(_translate("Form", "Give Awards"))
        self.comboBox_3.setPlaceholderText(_translate("Form", "Stadium"))
        self.comboBox_6.setPlaceholderText(_translate("Form", "Team1"))
        self.comboBox_7.setPlaceholderText(_translate("Form", "Team 2"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Enter std name"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "City"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "Capacity"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "Enter mng name"))
        self.pushButton_10.setText(_translate("Form", "Add"))
        self.pushButton_11.setText(_translate("Form", "Add"))
        self.comboBox_8.setPlaceholderText(_translate("Form", "Team"))
        self.comboBox_8.setItemText(0, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(1, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(2, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(3, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(4, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(5, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(6, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(7, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(8, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(9, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(10, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(11, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(12, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(13, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(14, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(15, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(16, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(17, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(18, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(19, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(20, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(21, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(22, _translate("Form", "New Item"))
        self.comboBox_8.setItemText(23, _translate("Form", "New Item"))
        self.comboBox_9.setPlaceholderText(_translate("Form", "Give Awards"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
